name: locally
description: This package helps developers create local notification in flutter, it extends the flutter local notification package and tries to make usage more simple and user friendly.
version: 1.0.5
authors:
  - samuelezedi@gmail.com
  - micatovin@gmail.com
homepage: https://github.com/samuelezedi/locally

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  timezone: ^0.7.0
  flutter_native_timezone: ^1.1.0
  flutter_local_notifications: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

